# Uncomment this line to define a global platform for your project
platform :ios, '8.0'

target 'PropperShopper' do
pod 'libPusher', '~> 1.6'
pod 'MBProgressHUD', '~> 0.8'
end

target 'PropperShopperTests' do

end

